### ISSUE TITLE
Samples don't seem to work

### ISSUE THREAD

**Issue by Saboton** [psp2dev/raylib4Vita_samples#1]
Hello, I am trying to get some of the samples to work but they all seem to crash on InitWindow() and I am not sure why. 

Using VitaSDK on Ubuntu 20.04 WSL, OLED Model PSVita and most recent version of examples and raylib4vita.

**Comment by psxdev** [comment]
share logs to see the problem
change ip to your pc in code in debugNetInit("192.168.1.12",18194,3); 

change ip for your pc where you want to show logs 

to see logs you can use a script like this


echo [HOST] debugnet listener up
echo [HOST] ready to have a lot of fun!!!
socat udp-recv:18194 stdout

**Comment by psxdev** [comment]
did you install shader compiler thing?
https://github.com/SonicMastr/PIB-Configuration-Tool

**Comment by Saboton** [comment]
> did you install shader compiler thing?
> https://github.com/SonicMastr/PIB-Configuration-Tool

I didn't, and installing that fixed it, samples work. Probably just a case of me not RTFM'ing, apologies.
