### ISSUE TITLE
Constantly getting C2-12828-1

### ISSUE THREAD

**Issue by degradka** [psp2dev/raylib4Vita_samples#2]
When compiling, I have 0 errors, but upon launching (any sample) I get C2-12828-1
Here are the logs:
```
[HOST] debugnet listener up
[HOST] ready to have a lot of fun!!!
[VITA][INFO]:debugnet initialized
[VITA][INFO]:Copyright (C) 2010,2020 Antonio Jose Ramos Marquez aka bigboss @psxdev
[VITA][INFO]:ready to have a lot of fun...
[VITA][INFO]: Initializing raylib 4.2
[VITA][INFO]: Supported raylib modules:
[VITA][INFO]:     > rcore:..... loaded (mandatory)
[VITA][INFO]:     > rlgl:...... loaded (mandatory)
[VITA][INFO]:     > rshapes:... loaded (optional)
[VITA][INFO]:     > rtextures:. loaded (optional)
[VITA][INFO]:     > rtext:..... loaded (optional)
[VITA][INFO]:     > rmodels:... loaded (optional)
[VITA][INFO]:     > raudio:.... loaded (optional)
```
After these, the [error](https://media.discordapp.net/attachments/578578242743697418/1041053703215513750/image.png) pops up
And here's the [dump file](https://github.com/psp2dev/raylib4Vita_samples/files/9995627/dump-file.zip) in case you need it

**Comment by psxdev** [comment]
Did you install first in your vita https://github.com/SonicMastr/Pigs-In-A-Blanket?

**Comment by degradka** [comment]
I totally forgot about this issue, it's resolved now.
